### ISSUE TITLE
Add regular day/night attenders

### ISSUE THREAD

**Issue by StatsRhian** [The-Strategy-Unit/nhp_outputs#241]
- [x] Update config
- [x] #243 
- [x] #244 

```
        ip_regular_day_attender:
          name: "Regular Day Attender"
          measures:
            - admissions
            - beddays
        ip_regular_night_attender:
          name: "Regular Night Attender"
          measures:
            - admissions
            - beddays
 ```

Another weird bug. There are no regular day attenders in the sample results file, but the waterfall indicates there are 10,000
<img width="892" alt="Capture" src="https://github.com/user-attachments/assets/c7872068-4680-4c55-b818-d832f1533da6">
